project_id = "oxdneiaojgwezxltivcl"

[functions.scrape-properties]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false
